# Generated by Django 3.2.7 on 2021-09-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_holder', models.CharField(max_length=100)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.bank')),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_id', models.IntegerField()),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=2000, null=True)),
                ('nickname', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('bank_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.bankaccount')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
