# Generated by Django 3.2.7 on 2021-09-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank_id',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='bank_account_id',
            new_name='bank_account',
        ),
    ]