# Generated by Django 3.2.7 on 2021-09-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210915_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status_id',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='method_id',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
    ]
