# Generated by Django 3.2.7 on 2021-09-16 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email'),
        ('products', '0002_auto_20210915_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dicount_percent',
            new_name='discount_percent',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
