# Generated by Django 3.2.7 on 2021-09-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210916_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatherlocation',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category_id',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviewimage',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='main_category_id',
            new_name='main_category',
        ),
        migrations.RenameField(
            model_name='userlike',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='userlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
