# Generated by Django 3.2.7 on 2021-09-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210916_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
